-- ============================================================
-- BCAPrime Subject Manager — supabase-subjects.sql
-- Supabase SQL Editor mein EK BAAR chalao.
-- Creates the `subjects` table + RLS for the Admin Subject Manager,
-- and the public/own moderation workflow (is_public + status).
-- ============================================================

create table if not exists public.subjects (
  id bigint generated by default as identity primary key,
  name text not null,
  code text not null default '',
  semester integer not null check (semester between 1 and 8),
  college text not null default 'all',
  status text not null default 'pending' check (status in ('pending','approved')),
  is_public boolean not null default false,
  created_by text not null default '',
  created_at timestamptz not null default now()
);

alter table public.subjects enable row level security;

-- Indexes for the filters (college + semester + status)
create index if not exists idx_subjects_college on public.subjects (college);
create index if not exists idx_subjects_semester on public.subjects (semester);
create index if not exists idx_subjects_status on public.subjects (status);
create index if not exists idx_subjects_is_public on public.subjects (is_public);

-- ============================================================
-- READ: creator apni pending subject turant use kar- sakta hai,
-- public subjects sab ko dikhte hain, admins sab dekhte hain.
-- ============================================================
drop policy if exists "Anyone can read public subjects" on public.subjects;
create policy "Public subjects or own pending"
on public.subjects for select
to anon, authenticated
using (
  is_public = true
  or (created_by <> '' and created_by = (auth.jwt() ->> 'sub'))
);

drop policy if exists "Admins can read all subjects" on public.subjects;
create policy "Admins can read all subjects"
on public.subjects for select
to authenticated
using (auth.jwt() -> 'app_metadata' ->> 'role' = 'admin');

-- ============================================================
-- INSERT: koi bhi pending (private) subject submit kar sakta hai.
-- Admin banaye subjects is_public = true; users pending + false.
-- ============================================================
drop policy if exists "Anyone can submit pending subjects" on public.subjects;
create policy "Anyone can submit subjects"
on public.subjects for insert
to anon, authenticated
with check (
  status = 'pending'
  and is_public = false
);

drop policy if exists "Admins can insert subject" on public.subjects;
create policy "Admins can insert subject"
on public.subjects for insert
to authenticated
with check (auth.jwt() -> 'app_metadata' ->> 'role' = 'admin');

-- ============================================================
-- ADMIN MANAGEMENT: update (edit / approve) + delete.
-- RLS policies with check guards ensure only admins mutate rows.
-- ============================================================
drop policy if exists "Admins can update subjects" on public.subjects;
create policy "Admins can update subjects"
on public.subjects for update
to authenticated
using (auth.jwt() -> 'app_metadata' ->> 'role' = 'admin')
with check (auth.jwt() -> 'app_metadata' ->> 'role' = 'admin');

drop policy if exists "Admins can delete subjects" on public.subjects;
create policy "Admins can delete subjects"
on public.subjects for delete
to authenticated
using (auth.jwt() -> 'app_metadata' ->> 'role' = 'admin');