create table if not exists public.resources (
  id bigint generated by default as identity primary key,
  title text not null,
  type text not null check (type in ('notes', 'pyq')),
  subject text not null default 'Community upload',
  college text not null default 'all',
  semester integer not null check (semester between 1 and 6),
  year integer not null check (year between 1 and 3),
  file_name text,
  file_path text,
  file_url text,
  status text not null default 'pending' check (status in ('pending', 'approved', 'archived')),
  downloads integer not null default 0,
  created_at timestamptz not null default now()
);

alter table public.resources enable row level security;

create policy "Anyone can read approved resources"
on public.resources for select
using (status = 'approved');

create policy "Authenticated admins can manage resources"
on public.resources for all
to authenticated
using (auth.jwt() ->> 'role' = 'admin')
with check (auth.jwt() ->> 'role' = 'admin');

insert into storage.buckets (id, name, public)
values ('resources', 'resources', true)
on conflict (id) do nothing;
-- no rows are returned
