create table if not exists public.resources (
  id bigint generated by default as identity primary key,
  title text not null,
  type text not null check (type in ('notes', 'pyq')),
  subject text not null default 'Community upload',
  college text not null default 'all',
  semester integer not null check (semester between 1 and 6),
  year integer not null check (year between 1 and 3),
  file_name text,
  file_path text,
  file_url text,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected', 'archived')),
  downloads integer not null default 0,
  created_at timestamptz not null default now()
);

do $$
begin
  alter table public.resources drop constraint if exists resources_status_check;
  alter table public.resources add constraint resources_status_check
    check (status in ('pending', 'approved', 'rejected', 'archived'));
end $$;

alter table public.resources enable row level security;

-- Track who uploaded each resource so users can see their own upload status.
alter table public.resources add column if not exists uploader_email text not null default '';

-- Community upvotes (ratings) so students can flag the most useful material.
alter table public.resources add column if not exists upvotes integer not null default 0;

drop policy if exists "Anyone can read approved resources" on public.resources;
create policy "Anyone can read resources"
on public.resources for select
using (true);

drop policy if exists "Anyone can submit pending resources" on public.resources;
create policy "Anyone can submit pending resources"
on public.resources for insert
to anon, authenticated
with check (status = 'pending');

-- NOTE: Temporary open-moderation policies so the direct admin bypass
-- (admin.html hard-coded login) can approve/reject/delete without a
-- Supabase session. Remove these two policies once you log in with a
-- real Supabase admin account (app_metadata.role = 'admin').
drop policy if exists "Temporary: open moderation for direct admin bypass" on public.resources;
create policy "Temporary: open moderation for direct admin bypass"
on public.resources for update
to anon, authenticated
using (true)
with check (true);

drop policy if exists "Temporary: open delete for direct admin bypass" on public.resources;
create policy "Temporary: open delete for direct admin bypass"
on public.resources for delete
to anon, authenticated
using (true);

drop policy if exists "Authenticated admins can manage resources" on public.resources;
create policy "Authenticated admins can manage resources"
on public.resources for all
to authenticated
using (auth.jwt() -> 'app_metadata' ->> 'role' = 'admin')
with check (auth.jwt() -> 'app_metadata' ->> 'role' = 'admin');

insert into storage.buckets (id, name, public)
values ('resources', 'resources', true)
on conflict (id) do nothing;

drop policy if exists "Anyone can upload resource files" on storage.objects;
create policy "Anyone can upload resource files"
on storage.objects for insert
to anon, authenticated
with check (bucket_id = 'resources');

drop policy if exists "Anyone can read resource files" on storage.objects;
create policy "Anyone can read resource files"
on storage.objects for select
to anon, authenticated
using (bucket_id = 'resources');

-- ============================================================
-- Web Push subscriptions (notifications feature)
-- ============================================================
create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  user_agent text,
  college text not null default 'all',
  semester integer,
  uid text,
  created_at timestamptz not null default now()
);

alter table public.push_subscriptions enable row level security;

-- Ensure new targeting columns exist on already-deployed databases.
alter table public.push_subscriptions add column if not exists college text not null default 'all';
alter table public.push_subscriptions add column if not exists semester integer;
alter table public.push_subscriptions add column if not exists uid text;

drop policy if exists "Anyone can register a push subscription" on public.push_subscriptions;
create policy "Anyone can register a push subscription"
on public.push_subscriptions for insert
to anon, authenticated
with check (true);

drop policy if exists "Anyone can refresh a push subscription" on public.push_subscriptions;
create policy "Anyone can refresh a push subscription"
on public.push_subscriptions for update
to anon, authenticated
using (true)
with check (true);

drop policy if exists "Anyone can remove their own subscription by endpoint" on public.push_subscriptions;
create policy "Anyone can remove their own subscription by endpoint"
on public.push_subscriptions for delete
to anon, authenticated
using (true);

-- ============================================================
-- Account-bound college & semester (device-independent)
-- Har account (Firebase uid) ki ek profile: college + semester.
-- Login par is profile se sync hota hai, taaki same account har
-- device par SAME college + semester rakhe (DU laptop / Glocal
-- phone waala data-conflict nahi ho sakta).
-- NOTE: App Firebase auth use karta hai (Supabase JWT nahi),
-- isliye ye open policies hain — exposure sirf college/sem hai.
-- ============================================================
create table if not exists public.user_profiles (
  uid text primary key,
  email text not null default '',
  college text not null default 'all',
  semester integer,
  updated_at timestamptz not null default now()
);

alter table public.user_profiles enable row level security;

drop policy if exists "Anyone can read user profiles" on public.user_profiles;
create policy "Anyone can read user profiles"
on public.user_profiles for select
to anon, authenticated
using (true);

drop policy if exists "Anyone can create user profiles" on public.user_profiles;
create policy "Anyone can create user profiles"
on public.user_profiles for insert
to anon, authenticated
with check (true);

drop policy if exists "Anyone can update user profiles" on public.user_profiles;
create policy "Anyone can update user profiles"
on public.user_profiles for update
to anon, authenticated
using (true)
with check (true);

-- ============================================================
-- Linked devices per account (WhatsApp-style device approval)
-- Har device ek device_id par register hota hai. Naya device login
-- karne par 'pending' rehta hai; koi already-approved device usse
-- approve karta hai (link_code ya push tap se). First device auto
-- approved (taaki lockout na ho).
-- ============================================================
create table if not exists public.device_sessions (
  id bigint generated by default as identity primary key,
  uid text not null,
  device_id text not null,
  device_name text not null default '',
  link_code text default '',
  status text not null default 'pending' check (status in ('pending','approved','denied')),
  created_at timestamptz not null default now(),
  approved_at timestamptz,
  unique (uid, device_id)
);

alter table public.device_sessions enable row level security;

drop policy if exists "Anyone can read device sessions" on public.device_sessions;
create policy "Anyone can read device sessions"
on public.device_sessions for select
to anon, authenticated
using (true);

drop policy if exists "Anyone can create device sessions" on public.device_sessions;
create policy "Anyone can create device sessions"
on public.device_sessions for insert
to anon, authenticated
with check (true);

drop policy if exists "Anyone can update device sessions" on public.device_sessions;
create policy "Anyone can update device sessions"
on public.device_sessions for update
to anon, authenticated
using (true)
with check (true);

-- ============================================================
-- QR login sessions (WhatsApp Web style desktop login)
-- Desktop ek pending session banata hai (3 min expiry). Logged-in
-- phone URL scan karke usse 'approved' karta hai apne uid ke saath;
-- desktop Realtime broadcast + polling dono se approval uthata hai,
-- row ko consume karta hai aur device_sessions me device approve
-- karta hai. Single-use + expiry enforced.
-- ============================================================
create table if not exists public.qr_login_sessions (
  session_id text primary key,
  status text not null default 'pending' check (status in ('pending','approved','denied')),
  uid text,
  email text default '',
  display_name text default '',
  device_name text default '',
  expires_at timestamptz not null,
  consumed_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.qr_login_sessions enable row level security;

drop policy if exists "Anyone can create qr sessions" on public.qr_login_sessions;
create policy "Anyone can create qr sessions"
on public.qr_login_sessions for insert
to anon, authenticated
with check (true);

drop policy if exists "Anyone can read qr sessions" on public.qr_login_sessions;
create policy "Anyone can read qr sessions"
on public.qr_login_sessions for select
to anon, authenticated
using (true);

drop policy if exists "Anyone can answer qr sessions" on public.qr_login_sessions;
create policy "Anyone can answer qr sessions"
on public.qr_login_sessions for update
to anon, authenticated
using (true)
with check (true);

drop policy if exists "Anyone can clear expired qr sessions" on public.qr_login_sessions;
create policy "Anyone can clear expired qr sessions"
on public.qr_login_sessions for delete
to anon, authenticated
using (true);

-- ============================================================
-- User feedback / bug reports
-- ============================================================
create table if not exists public.feedback (
  id bigint generated by default as identity primary key,
  kind text not null default 'idea' check (kind in ('bug','idea','question')),
  message text not null,
  contact text default '',
  user_email text default '',
  user_name text default '',
  screenshot_url text,
  page_url text,
  user_agent text,
  status text not null default 'open' check (status in ('open','resolved')),
  created_at timestamptz not null default now()
);

alter table public.feedback enable row level security;

-- App login Firebase se hota hai (Supabase JWT nahi), isliye insert anonymous
-- rehta hai. Page pe chuniye to issuer bhi nuach nahi: inset ansi read/delete sirf admin.
-- > insert pe aane nya nahi: login-gating app.js karta hai + user email/name auto.
drop policy if exists "Anyone can submit feedback" on public.feedback;
create policy "Anyone can submit feedback"
on public.feedback for insert
to anon, authenticated
with check (true);

-- Only admins can view, update or delete feedback.
drop policy if exists "Authenticated can view feedback" on public.feedback;
create policy "Admins can view feedback"
on public.feedback for select
to authenticated
using (auth.jwt() -> 'app_metadata' ->> 'role' = 'admin');

drop policy if exists "Authenticated can manage feedback" on public.feedback;
create policy "Admins can update feedback"
on public.feedback for update
to authenticated
using (auth.jwt() -> 'app_metadata' ->> 'role' = 'admin')
with check (auth.jwt() -> 'app_metadata' ->> 'role' = 'admin');

drop policy if exists "Authenticated can delete feedback" on public.feedback;
create policy "Admins can delete feedback"
on public.feedback for delete
to authenticated
using (auth.jwt() -> 'app_metadata' ->> 'role' = 'admin');

-- Storage bucket for feedback screenshots
insert into storage.buckets (id, name, public)
values ('feedback', 'feedback', true)
on conflict (id) do nothing;

drop policy if exists "Anyone can upload feedback screenshots" on storage.objects;
create policy "Anyone can upload feedback screenshots"
on storage.objects for insert
to anon, authenticated
with check (bucket_id = 'feedback');

drop policy if exists "Anyone can read feedback screenshots" on storage.objects;
create policy "Anyone can read feedback screenshots"
on storage.objects for select
to anon, authenticated
using (bucket_id = 'feedback');

-- Reading is intentionally NOT allowed via the anon key: only the Edge
-- Function (service_role) fetches subscriptions to send pushes.

