create table if not exists public.resources (
  id bigint generated by default as identity primary key,
  title text not null,
  type text not null check (type in ('notes', 'pyq')),
  subject text not null default 'Community upload',
  college text not null default 'all',
  semester integer not null check (semester between 1 and 6),
  year integer not null check (year between 1 and 3),
  file_name text,
  file_path text,
  file_url text,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected', 'archived')),
  downloads integer not null default 0,
  created_at timestamptz not null default now()
);

do $$
begin
  alter table public.resources drop constraint if exists resources_status_check;
  alter table public.resources add constraint resources_status_check
    check (status in ('pending', 'approved', 'rejected', 'archived'));
end $$;

alter table public.resources enable row level security;

drop policy if exists "Anyone can read approved resources" on public.resources;
create policy "Anyone can read approved resources"
on public.resources for select
using (status = 'approved');

drop policy if exists "Anyone can submit pending resources" on public.resources;
create policy "Anyone can submit pending resources"
on public.resources for insert
to anon, authenticated
with check (status = 'pending');

drop policy if exists "Authenticated admins can manage resources" on public.resources;
create policy "Authenticated admins can manage resources"
on public.resources for all
to authenticated
using (auth.jwt() -> 'app_metadata' ->> 'role' = 'admin')
with check (auth.jwt() -> 'app_metadata' ->> 'role' = 'admin');

insert into storage.buckets (id, name, public)
values ('resources', 'resources', true)
on conflict (id) do nothing;

drop policy if exists "Anyone can upload resource files" on storage.objects;
create policy "Anyone can upload resource files"
on storage.objects for insert
to anon, authenticated
with check (bucket_id = 'resources');

drop policy if exists "Anyone can read resource files" on storage.objects;
create policy "Anyone can read resource files"
on storage.objects for select
to anon, authenticated
using (bucket_id = 'resources');
