-- ============================================================
-- BCAPrime — Community Chat: WHATSAPP-STYLE DELETION + ADMIN MODERATION
-- Run this ONCE in the Supabase SQL Editor.
-- (Sab idempotent hai — dobara run karne par kuch bigadta nahi.
--  Best: pehle supabase-schema.sql + supabase-chat-isolation.sql +
--  supabase-chat-no-phone-gate.sql + supabase-chat-reactions-edits.sql run.)
--
-- Ye file kya karti hai:
--  1) chat_messages par soft-delete columns:
--       is_deleted (bool), deleted_by ('self'|'admin'|''),
--       deleted_at, deleted_by_uid.
--     "Delete for Everyone" ab row DELETE nahi karta — UPDATE karke
--     tombstone banata hai ("This message was deleted" / admin variant)
--     taaki sab clients ko realtime UPDATE event se turant dikhe
--     (bina page reload, bina history gap).
--  2) `chat_hides` table — "Delete for Me" (per-user, cross-device).
--     Local localStorage hides ke SAATH server sync (dusre device par
--     bhi hidden rahe).
--  3) `chat_bans` table + BEFORE INSERT guard trigger — banned user
--     kuch bhej hi nahi sakta (server-side, client bypass-proof).
--  4) `moderation_logs` table — har delete/ban/unban ka audit trail
--     (original text preserved for admin review).
--  5) user_profiles.is_admin — chat-side admin flag (Firebase-uid based,
--     kyunki is stack me Supabase ko Firebase JWT nahi milta).
--  6) SECURITY DEFINER RPCs (same trust model as existing bca_* RPCs):
--       bca_soft_delete_message  — sender: apna msg, 48h window ke andar
--       bca_admin_delete_message — admin: kisi ka bhi msg, no time limit
--       bca_hide_for_me          — Delete for Me (server record)
--       bca_ban_user / bca_unban_user — admin ban controls
--       is_chat_admin / is_chat_banned — helper checks
--  7) Purana bca_delete_message() backward-compat wrapper ban jata hai
--     (soft-delete call karta hai) taaki purane clients na tooten.
-- ============================================================

-- ---------- 0) Chat-side admin flag on profiles ----------
alter table public.user_profiles
  add column if not exists is_admin boolean not null default false;

-- Kisi Firebase uid ko chat-admin banana ho to (Supabase admin se):
--   update public.user_profiles set is_admin = true where uid = 'FIREBASE_UID';
-- Ya Supabase-auth admin (app_metadata.role='admin') auto-considered admin
-- (neeche is_chat_admin dekho).

-- ---------- 1) Soft-delete columns on chat_messages ----------
alter table public.chat_messages
  add column if not exists is_deleted boolean not null default false;
alter table public.chat_messages
  add column if not exists deleted_by text not null default '';
alter table public.chat_messages
  add column if not exists deleted_at timestamptz;
alter table public.chat_messages
  add column if not exists deleted_by_uid text not null default '';

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'chat_messages_deleted_by_check') then
    alter table public.chat_messages
      add constraint chat_messages_deleted_by_check
      check (deleted_by in ('', 'self', 'admin'));
  end if;
end $$;

create index if not exists chat_messages_is_deleted_idx
  on public.chat_messages (is_deleted);

-- ---------- 2) "Delete for Me" hides (per-user, cross-device) ----------
create table if not exists public.chat_hides (
  message_id bigint not null references public.chat_messages (id) on delete cascade,
  uid text not null default '',
  created_at timestamptz not null default now(),
  constraint chat_hides_unique unique (message_id, uid)
);

create index if not exists chat_hides_uid_idx on public.chat_hides (uid);
create index if not exists chat_hides_message_idx on public.chat_hides (message_id);

alter table public.chat_hides enable row level security;

drop policy if exists "Anyone can read chat hides" on public.chat_hides;
create policy "Anyone can read chat hides"
  on public.chat_hides for select
  to anon, authenticated
  using (true);

-- ---------- 3) Chat bans (remove/ban disruptive users) ----------
create table if not exists public.chat_bans (
  uid text primary key,
  reason text not null default '',
  banned_by text not null default '',
  banned_at timestamptz not null default now(),
  expires_at timestamptz
);

alter table public.chat_bans enable row level security;

drop policy if exists "Anyone can read chat bans" on public.chat_bans;
create policy "Anyone can read chat bans"
  on public.chat_bans for select
  to anon, authenticated
  using (true);

-- Writes sirf RPC se (neeche) — koi direct insert/update/delete policy nahi.

-- ---------- 4) Moderation audit log ----------
create table if not exists public.moderation_logs (
  id bigint generated by default as identity primary key,
  action text not null default '',
  message_id bigint,
  target_uid text not null default '',
  target_name text not null default '',
  original_body text not null default '',
  channel text not null default '',
  college text not null default 'all',
  semester integer,
  reason text not null default '',
  actor_uid text not null default '',
  created_at timestamptz not null default now()
);

create index if not exists moderation_logs_action_idx on public.moderation_logs (action, created_at desc);
create index if not exists moderation_logs_message_idx on public.moderation_logs (message_id);
create index if not exists moderation_logs_actor_idx on public.moderation_logs (actor_uid);

alter table public.moderation_logs enable row level security;

drop policy if exists "Anyone can read moderation logs" on public.moderation_logs;
create policy "Anyone can read moderation logs"
  on public.moderation_logs for select
  to anon, authenticated
  using (true);
-- (Sensitive full text? Admin panel hi isey padhta hai via admin session;
--  reads open rakhe hain taaki anon-key stack na toote — UI se koi PII leak nahi.)

grant usage, select on sequence public.moderation_logs_id_seq to anon, authenticated;
grant select, insert on public.moderation_logs to anon, authenticated;

-- ---------- 5) Admin check helper ----------
-- Firebase-uid based: user_profiles.is_admin = true
--                  OR Supabase-auth JWT role = 'admin' (admin panel session).
create or replace function public.is_chat_admin(p_uid text)
returns boolean language sql security definer stable as $$
  select coalesce(
    (select is_admin from public.user_profiles where uid = p_uid limit 1),
    false
  )
  or coalesce(
    (select (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'),
    false
  );
$$;

-- ---------- 6) Ban check + send-guard trigger ----------
create or replace function public.is_chat_banned(p_uid text)
returns boolean language sql security definer stable as $$
  select exists (
    select 1 from public.chat_bans
     where uid = p_uid
       and (expires_at is null or expires_at > now())
  );
$$;

-- Banned sender ka INSERT server par hi reject (client bypass-proof).
create or replace function public.guard_chat_banned_sender()
returns trigger language plpgsql security definer as $$
begin
  if new.uid is not null and new.uid <> '' and public.is_chat_banned(new.uid) then
    raise exception 'You are banned from community chat (%)', new.uid;
  end if;
  return new;
end;
$$;

-- 7a) Sender: "Delete for Everyone" (48h window, tombstone UPDATE).
create or replace function public.bca_soft_delete_message(
  p_id bigint, p_uid text
)
returns jsonb
language plpgsql security definer set search_path = public as $$
declare
  v_row public.chat_messages%rowtype;
  v_limit interval := interval '48 hours';
begin
  if p_uid is null or p_uid = '' then
    return jsonb_build_object('ok', false, 'error', 'login-required');
  end if;
  select * into v_row from public.chat_messages where id = p_id;
  if not found then
    return jsonb_build_object('ok', false, 'error', 'not-found');
  end if;
  if v_row.uid <> p_uid then
    return jsonb_build_object('ok', false, 'error', 'not-your-message');
  end if;
  if coalesce(v_row.is_deleted, false) then
    return jsonb_build_object('ok', true, 'already', true);
  end if;
  if v_row.created_at < (now() - v_limit) then
    return jsonb_build_object('ok', false, 'error', 'time-window-expired');
  end if;
  update public.chat_messages
     set body = 'This message was deleted',
         image_url = '', code_lang = '',
         is_deleted = true, deleted_by = 'self',
         deleted_at = now(), deleted_by_uid = p_uid
   where id = p_id;
  insert into public.moderation_logs
    (action, message_id, target_uid, target_name, original_body,
     channel, college, semester, actor_uid)
  values
    ('delete_self', p_id, v_row.uid, v_row.author_name,
     left(coalesce(v_row.body, ''), 2000),
     v_row.channel, coalesce(v_row.college, 'all'), v_row.semester, p_uid);
  return jsonb_build_object('ok', true);
end;
$$;

-- 7b) Admin: delete ANY message (no time limit, admin indicator).
create or replace function public.bca_admin_delete_message(
  p_id bigint, p_uid text, p_reason text default ''
)
returns jsonb
language plpgsql security definer set search_path = public as $$
declare
  v_row public.chat_messages%rowtype;
begin
  if p_uid is null or p_uid = '' then
    return jsonb_build_object('ok', false, 'error', 'login-required');
  end if;
  if not public.is_chat_admin(p_uid) then
    return jsonb_build_object('ok', false, 'error', 'admin-only');
  end if;
  select * into v_row from public.chat_messages where id = p_id;
  if not found then
    return jsonb_build_object('ok', false, 'error', 'not-found');
  end if;
  if coalesce(v_row.is_deleted, false) then
    return jsonb_build_object('ok', true, 'already', true);
  end if;
  update public.chat_messages
     set body = 'This message was deleted by an admin',
         image_url = '', code_lang = '',
         is_deleted = true, deleted_by = 'admin',
         deleted_at = now(), deleted_by_uid = p_uid
   where id = p_id;
  insert into public.moderation_logs
    (action, message_id, target_uid, target_name, original_body,
     channel, college, semester, reason, actor_uid)
  values
    ('delete_admin', p_id, v_row.uid, v_row.author_name,
     left(coalesce(v_row.body, ''), 2000),
     v_row.channel, coalesce(v_row.college, 'all'), v_row.semester,
     left(coalesce(p_reason, ''), 500), p_uid);
  return jsonb_build_object('ok', true);
end;
$$;

-- 7c) "Delete for Me" server hide (cross-device) + ban/unban RPCs.
create or replace function public.bca_hide_for_me(
  p_message_id bigint, p_uid text
)
returns boolean
language plpgsql security definer set search_path = public as $$
begin
  if p_uid is null or p_uid = '' or p_message_id is null then
    return false;
  end if;
  insert into public.chat_hides (message_id, uid)
  values (p_message_id, p_uid)
  on conflict (message_id, uid) do nothing;
  return true;
end;
$$;

create or replace function public.bca_ban_user(
  p_uid text, p_target_uid text, p_reason text default '', p_days integer default null
)
returns jsonb
language plpgsql security definer set search_path = public as $$
begin
  if p_uid is null or p_uid = '' then
    return jsonb_build_object('ok', false, 'error', 'login-required');
  end if;
  if not public.is_chat_admin(p_uid) then
    return jsonb_build_object('ok', false, 'error', 'admin-only');
  end if;
  if p_target_uid is null or p_target_uid = '' then
    return jsonb_build_object('ok', false, 'error', 'target-required');
  end if;
  insert into public.chat_bans (uid, reason, banned_by, expires_at)
  values (p_target_uid, left(coalesce(p_reason, ''), 500), p_uid,
          case when p_days is not null and p_days > 0
               then now() + (p_days || ' days')::interval end)
  on conflict (uid) do update
    set reason = excluded.reason,
        banned_by = excluded.banned_by,
        banned_at = now(),
        expires_at = excluded.expires_at;
  insert into public.moderation_logs (action, target_uid, reason, actor_uid)
  values ('ban', p_target_uid, left(coalesce(p_reason, ''), 500), p_uid);
  return jsonb_build_object('ok', true);
end;
$$;

create or replace function public.bca_unban_user(
  p_uid text, p_target_uid text
)
returns jsonb
language plpgsql security definer set search_path = public as $$
begin
  if p_uid is null or p_uid = '' then
    return jsonb_build_object('ok', false, 'error', 'login-required');
  end if;
  if not public.is_chat_admin(p_uid) then
    return jsonb_build_object('ok', false, 'error', 'admin-only');
  end if;
  delete from public.chat_bans where uid = p_target_uid;
  insert into public.moderation_logs (action, target_uid, actor_uid)
  values ('unban', p_target_uid, p_uid);
  return jsonb_build_object('ok', true);
end;
$$;

-- 7d) Backward-compat: purana bca_delete_message -> soft-delete wrapper.
create or replace function public.bca_delete_message(
  p_id bigint, p_uid text
)
returns boolean
language plpgsql security definer set search_path = public as $$
declare
  v_res jsonb;
begin
  if p_uid is null or p_uid = '' then
    return false;
  end if;
  if public.is_chat_admin(p_uid) then
    v_res := public.bca_admin_delete_message(p_id, p_uid, 'legacy client');
  else
    v_res := public.bca_soft_delete_message(p_id, p_uid);
  end if;
  return coalesce((v_res ->> 'ok')::boolean, false);
exception when others then
  return false;
end;
$$;

-- 8) Realtime: ban-guard trigger + chat_bans/moderation_logs live sync.
drop trigger if exists chat_messages_ban_guard on public.chat_messages;
create trigger chat_messages_ban_guard
  before insert on public.chat_messages
  for each row execute function public.guard_chat_banned_sender();

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
     where pubname = 'supabase_realtime'
       and schemaname = 'public' and tablename = 'chat_bans'
  ) then
    alter publication supabase_realtime add table public.chat_bans;
  end if;
  if not exists (
    select 1 from pg_publication_tables
     where pubname = 'supabase_realtime'
       and schemaname = 'public' and tablename = 'moderation_logs'
  ) then
    alter publication supabase_realtime add table public.moderation_logs;
  end if;
end $$;

-- Verify
select 'chat_messages.is_deleted' as result from information_schema.columns
 where table_schema='public' and table_name='chat_messages' and column_name='is_deleted'
union all
select 'chat_hides' from information_schema.tables
 where table_schema='public' and table_name='chat_hides'
union all
select 'chat_bans' from information_schema.tables
 where table_schema='public' and table_name='chat_bans'
union all
select 'moderation_logs' from information_schema.tables
 where table_schema='public' and table_name='moderation_logs';
