-- ============================================================
-- BCAPrime — Community Chat: REACTIONS + EDIT + DELETE (for everyone)
-- Run this ONCE in the Supabase SQL Editor.
-- (Sab idempotent hai — dobara run karne par kuch bigadta nahi.
--  Best: pehle supabase-schema.sql + supabase-chat-isolation.sql run.)
--
-- Ye file kya karti hai:
--  1) chat_messages par `edited_at` column (Edited tag).
--  2) `chat_reactions` table (👍 ❤️ 😂 … per-message).
--  3) SECURITY DEFINER RPC functions:
--        bca_edit_message    — sirf apna message edit (edited_at stamp)
--        bca_delete_message  — "delete for everyone" (author ya admin)
--        bca_toggle_reaction — reaction add/remove (room parent se copy)
--     Kyun RPC? Is stack me Firebase login chalta hai aur Supabase par
--     sirf anon/publishable key jaati hai — Postgres ko koi
--     request-scoped identity nahi milti (auth.uid()/jwt sub null).
--     RLS "uid = jwt sub" wali ownership kabhi prove nahi kar paati
--     (yahi purane delete ko block karta tha). SECURITY DEFINER
--     functions client-claimed uid par chalti hain — SAME trust model
--     jo app pehle se insert gate (is_phone_verified_student) me
--     use karta hai. Documented limitation of this stack.
--  4) chat_reactions ko supabase_realtime publication me add (live sync).
--  5) chat_messages UPDATE/DELETE events publication me already hain —
--     client unhe sunta hai (edit/delete real-time).
-- ============================================================

-- ---------- 1) Edited tag column ----------
alter table public.chat_messages
  add column if not exists edited_at timestamptz;

-- ---------- 2) Reactions table ----------
create table if not exists public.chat_reactions (
  id bigint generated by default as identity primary key,
  message_id bigint not null references public.chat_messages (id) on delete cascade,
  uid text not null default '',
  emoji text not null default '',
  -- Room stamp (copied from the parent message by bca_toggle_reaction)
  -- so the realtime transport can filter reactions by college+semester.
  college text not null default 'all',
  semester integer,
  created_at timestamptz not null default now(),
  constraint chat_reactions_emoji_len check (char_length(emoji) between 1 and 16),
  constraint chat_reactions_unique unique (message_id, uid, emoji)
);

create index if not exists chat_reactions_message_idx
  on public.chat_reactions (message_id);
create index if not exists chat_reactions_room_idx
  on public.chat_reactions (college, semester, message_id);

alter table public.chat_reactions enable row level security;

grant usage, select on sequence public.chat_reactions_id_seq to anon, authenticated;
grant select, insert, update, delete on public.chat_reactions to anon, authenticated;

-- READ: jaise chat messages, reactions bhi sabko dikhte hain.
drop policy if exists "Anyone can read chat reactions" on public.chat_reactions;
create policy "Anyone can read chat reactions"
  on public.chat_reactions for select
  to anon, authenticated
  using (true);

-- INSERT (fallback path — primary path RPC hai): valid message par,
-- sane emoji length, aur room stamp parent message se match karna
-- chahiye (cross-room realtime leakage rokne ke liye).
create or replace function public.is_reaction_on_room_message(
  p_message_id bigint, p_college text, p_sem integer
)
returns boolean language sql security definer stable as $$
  select exists (
    select 1 from public.chat_messages m
    where m.id = p_message_id
      and lower(coalesce(m.college,'all')) = lower(coalesce(nullif(trim(p_college),''),'all'))
      and m.semester is not distinct from p_sem
  );
$$;

drop policy if exists "Students can add chat reactions" on public.chat_reactions;
create policy "Students can add chat reactions"
  on public.chat_reactions for insert
  to anon, authenticated
  with check (
    uid <> ''
    and char_length(emoji) between 1 and 16
    and public.is_reaction_on_room_message(message_id, college, semester)
  );
-- DELETE policy nahi: removal bhi RPC (bca_toggle_reaction) se hota hai,
-- kyunki anon key par ownership RLS se prove ho hi nahi sakti.

-- ---------- 3) SECURITY DEFINER RPCs ----------

-- 3a) EDIT own message (sets edited_at → UI "Edited" tag).
create or replace function public.bca_edit_message(
  p_id bigint, p_uid text, p_body text
)
returns setof public.chat_messages
language plpgsql security definer set search_path = public as $$
begin
  if p_uid is null or p_uid = '' then
    raise exception 'uid required';
  end if;
  if p_body is null or char_length(p_body) = 0 then
    raise exception 'body required';
  end if;
  if char_length(p_body) > 4000 then
    raise exception 'body too long (max 4000)';
  end if;
  return query
  update public.chat_messages
     set body = p_body,
         edited_at = now()
   where id = p_id
     and uid = p_uid            -- author-only
  returning *;
  if not found then
    raise exception 'not allowed to edit this message';
  end if;
end;
$$;

-- 3b) DELETE for EVERYONE (author, or Supabase-admin JWT role).
--     Hard delete → realtime DELETE event → sab clients se turant gayab.
--     (Purana RLS delete policy jwt-sub par thi jo is stack me kabhi
--      match nahi hoti thi — isliye delete kaam nahi karta tha.)
create or replace function public.bca_delete_message(
  p_id bigint, p_uid text
)
returns boolean
language plpgsql security definer set search_path = public as $$
declare
  v_admin boolean := false;
begin
  if p_uid is null or p_uid = '' then
    return false;
  end if;
  begin
    v_admin := coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') = 'admin';
  exception when others then
    v_admin := false;
  end;
  delete from public.chat_messages
   where id = p_id
     and (uid = p_uid or v_admin);
  return found;
end;
$$;

-- 3c) TOGGLE a reaction (add/remove). Room stamp parent message se
--     copy hota hai — client college/semester specify nahi karta.
create or replace function public.bca_toggle_reaction(
  p_message_id bigint, p_uid text, p_emoji text, p_add boolean
)
returns void
language plpgsql security definer set search_path = public as $$
declare
  v_college text;
  v_sem integer;
begin
  if p_uid is null or p_uid = '' then
    raise exception 'uid required';
  end if;
  if p_emoji is null or char_length(p_emoji) not between 1 and 16 then
    raise exception 'invalid emoji';
  end if;

  select college, semester into v_college, v_sem
    from public.chat_messages
   where id = p_message_id;
  if not found then
    raise exception 'message not found';
  end if;

  if coalesce(p_add, false) then
    insert into public.chat_reactions (message_id, uid, emoji, college, semester)
    values (p_message_id, p_uid, p_emoji, coalesce(v_college,'all'), v_sem)
    on conflict (message_id, uid, emoji) do nothing;
  else
    delete from public.chat_reactions
     where message_id = p_message_id
       and uid = p_uid
       and emoji = p_emoji;
  end if;
end;
$$;

-- ---------- 4) Realtime publication (reactions live sync) ----------
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'chat_reactions'
  ) then
    alter publication supabase_realtime add table public.chat_reactions;
  end if;
end $$;

-- chat_messages already in the publication (schema/isolation SQL) →
-- its UPDATE (edits) + DELETE (for-everyone) events flow to clients.

-- ---------- Verify ----------
select 'chat_reactions' as result from information_schema.tables
 where table_schema='public' and table_name='chat_reactions'
union all
select 'edited_at' from information_schema.columns
 where table_schema='public' and table_name='chat_messages' and column_name='edited_at';

