-- ============================================================
-- BCAPrime — Guest Mode + Download Security (storage lockdown)
-- ============================================================
-- Run this in the Supabase SQL editor (project: kjesjaakjddfxykisssh).
--
-- KYA KARTA HAI:
--   1) 'resources' bucket ko PRIVATE bana deta hai -> ab koi bhi
--      direct/guest URL se raw PDF (public /object/public/... link)
--      fetch NAHI kar payega. Storage level par 403 aayega.
--   2) Guest preview quota ka ek chhota audit table + SECURITY
--      DEFINER function -> Edge Function (sign-resource) server-side
--      limit enforce karta hai (client counter ke upar ek aur layer).
--
-- IMPORTANT (deploy order):
--   -> Pehle Edge Function deploy karo:  supabase functions deploy sign-resource
--   -> Phir ye SQL run karo (bucket private).
--   -> Saath hi naya frontend deploy karo jo signed URLs use karta hai.
--   Warning: bucket private hone par PURANE public file_url links
--   kaam karna band kar denge (wo intended hai — wo insecure the).
-- ============================================================

-- ------------------------------------------------------------
-- 1) PRIVATE BUCKET: direct public reads block
--    (Signed URLs service-role se bante hain -> RLS bypass, safe.)
-- ------------------------------------------------------------
update storage.buckets set public = false where id = 'resources';

-- Agar koi purani public read policy bachi ho to hata do.
drop policy if exists "Anyone can read resource files" on storage.objects;
drop policy if exists "Authenticated users can read resource files" on storage.objects;

-- NOTE: upload insert policy ("Anyone can upload resource files") ko
-- JAANBOOJH kar chhod diya gaya hai taaki upload flow na toote.
-- Uploads frontend par requireAccount() se gated hain (sign-up wall).

-- ------------------------------------------------------------
-- 2) GUEST PREVIEW QUOTA (server-side safety net)
--    Client counter (localStorage/sessionStorage) ke upar ek extra
--    layer: Edge Function har guest preview yahan log karta hai.
--    RLS enabled hai par koi client policy NAHI -> sirf SECURITY
--    DEFINER function (ya service role) hi is table ko chhu sakta hai.
-- ------------------------------------------------------------
create table if not exists public.guest_preview_log (
  id          bigint generated by default as identity primary key,
  guest_id    text not null,
  resource_id text,
  created_at  timestamptz not null default now()
);

alter table public.guest_preview_log enable row level security;

-- Koi bhi anon/authenticated direct access mana hai.
-- (Purani policies clean rakho — idempotent.)
drop policy if exists "No client access to guest_preview_log" on public.guest_preview_log;
-- (koi select/insert policy banayi hi nahi = default deny)

create index if not exists guest_preview_log_guest_idx
  on public.guest_preview_log (guest_id, created_at);

-- Server-side guest preview AUDIT LOG.
-- SECURITY DEFINER => function owner ke roop me chalta hai, isliye
-- service role bhi theek se call kar paayega aur RLS bypass hoga.
-- NOTE: preview quota ab khatam ho gayi hai (Guest Mode = unlimited
-- reading). Ye function ab sirf analytics logging ke liye hai — hamesha
-- true return karti hai taaki preview kabhi block na ho.
create or replace function public.consume_guest_preview(p_guest_id text, p_resource_id text)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_count int;
begin
  -- Basic validation: guest id chhoti aur meaningful honi chahiye.
  if p_guest_id is null or length(p_guest_id) < 8 or length(p_guest_id) > 80 then
    return false;
  end if;

  -- Audit: kaunsi guest ne kaunsi file kab dekhi (sirf analytics ke liye).
  insert into public.guest_preview_log (guest_id, resource_id)
  values (p_guest_id, p_resource_id);

  -- NO QUOTA: reading unlimited hai — hamesha allow.
  return true;
end;
$$;

-- Edge Function service-role key se call karegi; grant defensive rakhlo.
revoke all on function public.consume_guest_preview(text, text) from public, anon;
grant  execute on function public.consume_guest_preview(text, text) to service_role;

-- ============================================================
-- VERIFY (optional):
--   select id, public from storage.buckets where id = 'resources'; -- public=false
--   select * from public.guest_preview_log order by created_at desc limit 5;
-- ============================================================